Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: C:\Users\NUTHAN R\sqs-deploy\hello_world
      Runtime: python3.11
      Architectures:
        - x86_64