name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Modify to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Modify to your desired region
      - run: sam build --use-container

      - name: Deploy SAM Application
        run: sam deploy --config-env default --capabilities CAPABILITY_IAM --profile myprofile
